# Generated by Django 5.2.3 on 2025-07-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
