# Generated by Django 5.2.3 on 2025-07-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Interface', '0002_userattempt_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text="URL of the user's profile picture hosted externally.", max_length=500, null=True),
        ),
    ]
