# Generated by Django 5.2.3 on 2025-07-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Interface', '0003_userprofile_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, help_text="User's mobile number (e.g., +919876543210).", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year',
            field=models.CharField(blank=True, help_text='The academic year of the user (e.g., 2023-2024).', max_length=10, null=True),
        ),
    ]
