# Generated by Django 5.2.3 on 2025-07-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Interface', '0004_userprofile_mobile_number_userprofile_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='year',
            new_name='academic_year',
        ),
    ]
